name: OWASP Dependency Check scan

on:
  push:
    branches: 
      - master 
  pull_request: {}
  workflow_dispatch:

jobs:
  dependency_check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' 
    
    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        elif [ -f yarn.lock ]; then
          yarn install --frozen-lockfile
        else
          echo "No package manager lockfile found."
          exit 1

    - name: Install OWASP Dependency Check
      run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.1.2/dependency-check-8.1.2-release.zip
        unzip dependency-check-8.1.2-release.zip -d dependency-check
        chmod +x dependency-check/bin/dependency-check.sh

    - name: Run OWASP Dependency Check
      run: |
        dependency-check/bin/dependency-check.sh --project "P4_DDoS" --scan . --format "ALL" --out dependency-check-report
    
    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v3
      if: ${{ always () }}
      with:
        name: dependency-check-report
        path: dependency-check-report

